### ISSUE TITLE
AlpiMaps crashes on start

### ISSUE THREAD

**Issue by FabulousOne** [Akylas/alpimaps#5]
I discovered AlpiMaps recently, and had it installed on my phone. It worked as far as I could test it. But when I updated to the new versions (2.0.0.227/8/9), AlpiMaps crashes on the splash screen.
I tried to uninstall it and reinstall an older version (2.0.0.226), but this one crashes now too.
My phone is a Fairphone 3 with an Android 11 custom ROM (/e/ 1.8.1) with MicroG.
Is there any way to get some logs in order to fix this crash?
Thanks!

**Comment by farfromrefug** [comment]
@FabulousOne thanks for reporting this. I have been fighting that issue that I can't reproduce here. Would you by any chance be rooted and able to send me a logcat of the crash ?

**Comment by FabulousOne** [comment]
Yes, I am rooted. Could you tell me how to log, please?

**Comment by farfromrefug** [comment]
@FabulousOne the easiest way for you would be to install matlog on fdroid. Launch it first to.ensure it has permissions. 
Then re create the crash, open matlog, save to a file and share that file here.
Thanks a lot for helping me!

**Comment by FabulousOne** [comment]
Thank you for taking time to look into this issue. 
Here are the logs, I hope it is usable like this (for me, it looks like Chinese...)

/home/fwild/Schreibtisch/logs-2023-02-19-09-10-20.zip

**Comment by farfromrefug** [comment]
@FabulousOne thanks for the log. Sadly there is nothing in there :s
Did you:
* open matlog. THere you can even clear from the top right menu. and ensure it is not "paused"
* did matlog asked for root permission?
* open alpimaps so that it crashes
* re open matlog and get the log.

otherwise are you on windows / mac / linux?

**Comment by FabulousOne** [comment]
Hi @farfromrefug , 
so I redid the whole thing with your instructions. Yes, it has root permission. Have a look at it now: 
mtp://Fairphone_FP3_A209FYLF0202/Interner%20gemeinsamer%20Speicher/matlog/saved_logs/logs-2023-02-19-22-53-32.zip

**Comment by FabulousOne** [comment]
Oh man, you're so cool! Thank you very much. 
I really like your app, so lightweight and useful, especially for hiking. 

Thanks for your work!

**Comment by farfromrefug** [comment]
@FabulousOne thanks a lot. If you like it i ll explain to you how it should really be used. What country do you live in?
Also there should be an update. Can you tell me if it works ?

**Comment by FabulousOne** [comment]
Hi @farfromrefug thank you very much, it works now!
Yes, I'd like some explanation how to use it. I am German, but living in France. 
Cheers!

**Comment by farfromrefug** [comment]
@FabulousOne ok that is a great news as i live in France and thus i already have all the data built.
So that you understand AlpiMaps expect offline data in a `alpimaps_mbtiles` folder on your sdcard. With those data it can do all of its operations (mapping, rooting, geocoding...) without the need for internet.
Here is an example of how it can look like
![image](https://user-images.githubusercontent.com/655344/221211543-91248580-5315-4edc-ba95-477592203771.png)
* Top level data are for world mapping. The idea is to be able to render the whole world at  low level. `routes` stands for hiking/cycling routes. So you can get main hiking/cycling roads worldwide.
* each subfolder represents a zone/country:
   - france_full.mbtiles: the whole france map. Equivalent to osm maps with a few changes (removed a few things and added others). All centered around hiking/cycling
   - etiles files: elevation/hillshade data. Gives you hillshading, slope percentages, elevation profiles and any point elevation
   - *contours*.mbtiles: give you elevation contour lines
   - *routes*.mbtiles: give you hiking/cycling routes at all levels
   - vtiles files: give you full routing queries with direction instructions for car/pedestrian,cycling... It also can give you surface stats like komoot does
   - nutigeodb files: gives you geocoding/reverse geocoding. You can search for a lot of things offline. This one i am not 100% happy with yet.
   
   
If you are interested you can:
* create a `alpimaps_mbtiles` folder on your sdcard
* download world data (optional) from [here](http://gofile.me/4pKGL/o0bbJNNPr) and extract it directly in  `alpimaps_mbtiles`
* download france data (optional) from [here](http://gofile.me/4pKGL/sTIcA6I3L) and extract it directly in  `alpimaps_mbtiles`

Let me know if you need any help

**Comment by FabulousOne** [comment]
@farfromrefug Thank you very much. I was able to import the maps, and it works great!
But I had some maps before installing your map. Does this works by default, or was it because Alpimaps used my Organic Maps folder?

**Comment by farfromrefug** [comment]
@FabulousOne the only map you might have had working before is osm online maps which is loaded by default when no local data is found.
I dont use organic maps.
