### ISSUE TITLE
brightness is set to maximum, and it's blinding

### ISSUE THREAD

**Issue by obibon** [Akylas/alpimaps#6]
Somewhat related to #1, I guess.
Since the last update (running 2.0.0.232 from F-Droid), if I open the app, the screen brightness is set to maximum (or it feels like it). I try putting it in dark mode, but changes nothing. Although, whoever uses dark mode doesn't need much brightness...

I tried the settings, and couldn't find anything... but I can't look at the screen to look for stuff, it's way too bright.

Is there a way for it not to change the brightness at all, so that we can control that from the general settings on the phone? Not to sound rude, but I don't see the purpose of a map app tweaking the brightness settings.

Thanks for the app and the hard work, I'm looking forward to be able to use it again.

**Comment by farfromrefug** [comment]
@obibon those options are never on by default. Whatever the theme. 
Now as for those buttons not being really visible I agree. But it is also on purpose. I want the map to remain the main focus and I dont want too many buttons to clutter it.
In the mean time i like to have those buttons always here so that you can access them fast. They are especially useful while on a bike and needing to activate/deactivate for navigation 
I am always open to suggestions though !
